# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativity_app', '0002_auto_20181212_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativity',
            name='main_photo',
            field=models.ImageField(upload_to='media/images/creativity/', verbose_name='Основное фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/images/album/', verbose_name='Фото'),
        ),
    ]
