# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creativity_app', '0003_auto_20181212_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativity',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
